# Generated by Django 3.2 on 2021-04-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='description',
            field=models.CharField(max_length=600),
        ),
    ]
