# Generated by Django 3.2 on 2021-04-19 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_api', '0003_rename_file_file_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='User_data',
        ),
    ]
